export const BoardConstants = {
    SET_ALL_PROJECTS:'SET_ALL_PROJECTS',
    SET_FLOWCHART:'SET_FLOWCHART',
    SET_LOADING:'SET_LOADING',
    ADD_NODE:'ADD_NODE',
    DELETE_SELECTED:'DELETE_SELECTED',
    ADD_EDGE:'ADD_EDGE',
    SET_SUGGESTIONS:'SET_SUGGESTIONS',
    SET_CURRENT_NODE_DETAILS:'SET_CURRENT_NODE_DETAILS'
}