export const FosConstants = {
    SET_ALL_PROJECTS:'SET_ALL_PROJECTS',
    SET_FOS_FLOWCHART:'SET_FOS_FLOWCHART',
    SET_FOS_LOADING:'SET_FOS_LOADING',
    ADD_FOS_NODE:'ADD_FOS_NODE',
    DELETE_FOS_SELECTED:'DELETE_FOS_SELECTED',
    ADD_FOS_EDGE:'ADD_FOS_EDGE',
    SET_FOS_SUGGESTIONS:'SET_FOS_SUGGESTIONS',
    SET_FOS_CURRENT_NODE_DETAILS:'SET_FOS_CURRENT_NODE_DETAILS'
}